language: node_js
node_js:
  - "node"
env:
  global:
  - secure: exGXNqedTvpYe0wsUIlYGjgf1IX4L65vKFDge2vz1ybUIVqChw5u27N01xKvYLzj9ordes93gU/B7ighySUqAv+cTNJhANLM2VzcjgZbRxni9eAV6Z18lmXwfR81zr8nEgmNGcgeVDgVdgDY/OnVlChVuywtGFzludbpK1nqsSKNnk0qQ59oSkRfnW0S0Ea7fxrk4FVRhekD3nrjNJDpNNTspNC896jNTulCHiFkl0UY73SEc4VB0PgP5UV1gsu84XpLBPE/6hD/dn/KWwBeoDqW+NhWa3cFVR0CgjaVxdp/S7qk7/jjKocvuNOPYMk4qaDZJ9TRyiX4RKKRM4eEhmxYSMAuDkOKHsTDU4krxPS5P6WIKYAvalN69t1VRCWRJPumqoLehYbhCNlXLBehuYJ4H+QVJTYZVaiU5RSUVxj/owR5bl60esSMtFtuluW2jzoT2iKZmiM5UQ74pkoa1MRbD/Vxc6zmK+K3VPenu6gPlGYiv7LfHZiDXE8L86p2jOQDLBXZltqrmMDxIsthTBkvR+baATpB+YgdhxjVHN8AlODXBIXfbhsLGsx3zITXav+vKLjOPfKamQrHEEZz7G8hsrdPG2+JZfej/wviJrtdlWvfBMM6aXp1l28hbSEa2jIqULqMez98Fv54pdxL8XDNzlTp0ac1rTypnDqXEOA=
  - secure: KvgHgThJNx7OIrCYaqKwucRX3fgvPxm6+ktZlF4XNq3qm0B0Hh/TO546IQJk3b5Ki/3h40cPisW4/OgsLv1pvYAK6WfGPFCrhOsvyhH1pM7Z14CWACrzeXkND0qY0+vTr+MTOoOx4Pp5Dbm7GaBZ8S1SlEHNLNXsSYQzwDIozHUAQc0F2gYnaHF+NLApqfiWRZR0tYHIIMcp+xzcVeZJNkMqEIUVdGEBSVpabJavd+znPegOoaZHnwcjXJnTOkojmBxxeEg9Qvn9JBrIwqMXdEmP855x3K7c67nKy3mMvFH5Y5V/wr/IcmJLTxaj3w46yyQyBVLip6sU1xtCFfa6YdbmTQny6exjFhJ5xH0YVrBcIA23mVdUYR50NANFcd4bbmrVp+52KttaODPinoZkyCvgeC/RpyjZrCINLd9qLgsh4GUePesPj01pTNMZ1Cmf9uaftHqxWs8crk17wQvcz0rIq+zjefPOCbISK5Jl8uYytKFdIYRny6HGSmL8swXqqQ7MWOPRO3FVjaZ6hMP+dlQYT4UloL+nQQjxpi6LA8STjpgkuwUv7g1NwiLI0qo2aCEPn+yI1xru19tVP0APIWyxXGjQqI/MPtIWkkKtDQaka/GApYgvZ2Hqydc2CLnSUPxYpOgLhyxPlI7nuFHWBnxfc4zSsezon4fh5CBVmSQ=
jobs:
  include:
    - stage: test
      before_install:
        - npm install
      if: branch != master OR type != push
      script:
        - npm run build

    - stage: deploy
      before_install:
        - pip install --user awscli
        - npm install
      if: branch = master AND type IN (push)
      script:
        - npm run build
      after_success:
        - npm run deploy
