version: '3'
networks:
  main: {}

services:
  client:
    build: .
    image: client
    volumes:
      - ./src:/app/src
    networks:
      - main
    ports:
      - 3000:3000
    entrypoint:
      - npm
      - run
      - start
